name: 1.1$(rev:.r) # build numbering format

variables:
  BuildConfiguration: 'Release'
  FolderToPack: 'Application'
  SolutionName: 'MLH.WebUtilities.sln'
  ApplicationSubPath: 'MLH.WebUtilities' # The logic doesn't use the full repository name, therefore we cant use the build variable
  ReSharperSettingsFileName: 'CISettings_NuGet.DotSettings'

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

jobs:
- job: 'BuildAndPublishToNuGet'
  displayName: 'Build and publish to NuGet'
  pool:
    name: Azure Pipelines
    vmImage: windows-2019 # note that the Resharper CLT will only work on a windows machine or container
  steps:
  - checkout: self
  - checkout: ALMStuff
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Initialize_And_Test.yaml@ALMStuff
    parameters:
      BuildConfiguration: $(BuildConfiguration)
      SolutionName: $(SolutionName)
      ApplicationSubPath: $(ApplicationSubPath)
      ReSharperSettingsFileName: $(ReSharperSettingsFileName)
  - template: AzureDevOps/BuildTemplates/NetCore/Steps/Pack_And_Publish_To_NuGet.yaml@ALMStuff
    parameters:
      FolderToPack: $(FolderToPack)